//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("testModel1", "fk_collaborateur_id_abonnement", "Agent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Agent_), "Abonnement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Abonnement_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_theme_id_abonnement", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Theme_), "Abonnement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Abonnement_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_agent", "Type", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Ensiie.projet3.Models.Type_), "Agent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Agent_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_avis_collaborateur", "Agent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Agent_), "Avis_news", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Avis_news_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_commentaire_collaborateur", "Agent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Agent_), "Commentaire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Commentaire_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_like_news_collaborateur", "Agent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Agent_), "Like_news", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Like_news_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_message_collaborateur", "Agent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Agent_), "Message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Message_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_poster_news_collaborateur", "Agent", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Agent_), "News", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.News_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_avis_news", "News", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.News_), "Avis_news", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Avis_news_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_comm_theme_id", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Theme_), "Commentaire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Commentaire_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_message_id", "Message", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Message_), "Commentaire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Commentaire_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_like_news_news", "News", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.News_), "Like_news", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Like_news_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_theme_id", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Theme_), "Message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Message_), true)]
[assembly: EdmRelationshipAttribute("testModel1", "fk_theme_id_stat", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Ensiie.projet3.Models.Theme_), "Stat", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Ensiie.projet3.Models.Stat_), true)]

#endregion

namespace Ensiie.projet3.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class testEntities8 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new testEntities8 object using the connection string found in the 'testEntities8' section of the application configuration file.
        /// </summary>
        public testEntities8() : base("name=testEntities8", "testEntities8")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities8 object.
        /// </summary>
        public testEntities8(string connectionString) : base(connectionString, "testEntities8")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities8 object.
        /// </summary>
        public testEntities8(EntityConnection connection) : base(connection, "testEntities8")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Abonnement_> Abonnement
        {
            get
            {
                if ((_Abonnement == null))
                {
                    _Abonnement = base.CreateObjectSet<Abonnement_>("Abonnement");
                }
                return _Abonnement;
            }
        }
        private ObjectSet<Abonnement_> _Abonnement;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Agent_> Agent
        {
            get
            {
                if ((_Agent == null))
                {
                    _Agent = base.CreateObjectSet<Agent_>("Agent");
                }
                return _Agent;
            }
        }
        private ObjectSet<Agent_> _Agent;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Avis_news_> Avis_news
        {
            get
            {
                if ((_Avis_news == null))
                {
                    _Avis_news = base.CreateObjectSet<Avis_news_>("Avis_news");
                }
                return _Avis_news;
            }
        }
        private ObjectSet<Avis_news_> _Avis_news;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Commentaire_> Commentaire
        {
            get
            {
                if ((_Commentaire == null))
                {
                    _Commentaire = base.CreateObjectSet<Commentaire_>("Commentaire");
                }
                return _Commentaire;
            }
        }
        private ObjectSet<Commentaire_> _Commentaire;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Like_news_> Like_news
        {
            get
            {
                if ((_Like_news == null))
                {
                    _Like_news = base.CreateObjectSet<Like_news_>("Like_news");
                }
                return _Like_news;
            }
        }
        private ObjectSet<Like_news_> _Like_news;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message_> Message
        {
            get
            {
                if ((_Message == null))
                {
                    _Message = base.CreateObjectSet<Message_>("Message");
                }
                return _Message;
            }
        }
        private ObjectSet<Message_> _Message;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<News_> News
        {
            get
            {
                if ((_News == null))
                {
                    _News = base.CreateObjectSet<News_>("News");
                }
                return _News;
            }
        }
        private ObjectSet<News_> _News;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stat_> Stat
        {
            get
            {
                if ((_Stat == null))
                {
                    _Stat = base.CreateObjectSet<Stat_>("Stat");
                }
                return _Stat;
            }
        }
        private ObjectSet<Stat_> _Stat;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Theme_> Theme
        {
            get
            {
                if ((_Theme == null))
                {
                    _Theme = base.CreateObjectSet<Theme_>("Theme");
                }
                return _Theme;
            }
        }
        private ObjectSet<Theme_> _Theme;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Type_> Type
        {
            get
            {
                if ((_Type == null))
                {
                    _Type = base.CreateObjectSet<Type_>("Type");
                }
                return _Type;
            }
        }
        private ObjectSet<Type_> _Type;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<stat_light_> stat_light
        {
            get
            {
                if ((_stat_light == null))
                {
                    _stat_light = base.CreateObjectSet<stat_light_>("stat_light");
                }
                return _stat_light;
            }
        }
        private ObjectSet<stat_light_> _stat_light;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Abonnement EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAbonnement(Abonnement_ abonnement_)
        {
            base.AddObject("Abonnement", abonnement_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Agent EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAgent(Agent_ agent_)
        {
            base.AddObject("Agent", agent_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Avis_news EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAvis_news(Avis_news_ avis_news_)
        {
            base.AddObject("Avis_news", avis_news_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Commentaire EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommentaire(Commentaire_ commentaire_)
        {
            base.AddObject("Commentaire", commentaire_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Like_news EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLike_news(Like_news_ like_news_)
        {
            base.AddObject("Like_news", like_news_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage(Message_ message_)
        {
            base.AddObject("Message", message_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the News EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNews(News_ news_)
        {
            base.AddObject("News", news_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stat EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStat(Stat_ stat_)
        {
            base.AddObject("Stat", stat_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Theme EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTheme(Theme_ theme_)
        {
            base.AddObject("Theme", theme_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Type EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToType(Type_ type_)
        {
            base.AddObject("Type", type_);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the stat_light EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostat_light(stat_light_ stat_light_)
        {
            base.AddObject("stat_light", stat_light_);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Abonnement_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Abonnement_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Abonnement_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Abonnement_ CreateAbonnement_(global::System.Int32 id)
        {
            Abonnement_ abonnement_ = new Abonnement_();
            abonnement_.id = id;
            return abonnement_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> theme_id
        {
            get
            {
                return _theme_id;
            }
            set
            {
                Ontheme_idChanging(value);
                ReportPropertyChanging("theme_id");
                _theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("theme_id");
                Ontheme_idChanged();
            }
        }
        private Nullable<global::System.Int32> _theme_id;
        partial void Ontheme_idChanging(Nullable<global::System.Int32> value);
        partial void Ontheme_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> collaborateur_id
        {
            get
            {
                return _collaborateur_id;
            }
            set
            {
                Oncollaborateur_idChanging(value);
                ReportPropertyChanging("collaborateur_id");
                _collaborateur_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collaborateur_id");
                Oncollaborateur_idChanged();
            }
        }
        private Nullable<global::System.Int32> _collaborateur_id;
        partial void Oncollaborateur_idChanging(Nullable<global::System.Int32> value);
        partial void Oncollaborateur_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_collaborateur_id_abonnement", "Agent")]
        public Agent_ Agent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_collaborateur_id_abonnement", "Agent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_collaborateur_id_abonnement", "Agent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Agent_> AgentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_collaborateur_id_abonnement", "Agent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Agent_>("testModel1.fk_collaborateur_id_abonnement", "Agent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_theme_id_abonnement", "Theme")]
        public Theme_ Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id_abonnement", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id_abonnement", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme_> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id_abonnement", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme_>("testModel1.fk_theme_id_abonnement", "Theme", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Agent_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Agent_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Agent_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static Agent_ CreateAgent_(global::System.Int32 id, global::System.String name, global::System.String first_name, global::System.Int32 type, global::System.String password)
        {
            Agent_ agent_ = new Agent_();
            agent_.id = id;
            agent_.name = name;
            agent_.first_name = first_name;
            agent_.type = type;
            agent_.password = password;
            return agent_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Int32 _type;
        partial void OntypeChanging(global::System.Int32 value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dating
        {
            get
            {
                return _dating;
            }
            set
            {
                OndatingChanging(value);
                ReportPropertyChanging("dating");
                _dating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dating");
                OndatingChanged();
            }
        }
        private Nullable<global::System.DateTime> _dating;
        partial void OndatingChanging(Nullable<global::System.DateTime> value);
        partial void OndatingChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_collaborateur_id_abonnement", "Abonnement")]
        public EntityCollection<Abonnement_> Abonnement
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Abonnement_>("testModel1.fk_collaborateur_id_abonnement", "Abonnement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Abonnement_>("testModel1.fk_collaborateur_id_abonnement", "Abonnement", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_agent", "Type")]
        public Type_ Type1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Type_>("testModel1.fk_agent", "Type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Type_>("testModel1.fk_agent", "Type").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Type_> Type1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Type_>("testModel1.fk_agent", "Type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Type_>("testModel1.fk_agent", "Type", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_avis_collaborateur", "Avis_news")]
        public EntityCollection<Avis_news_> Avis_news
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Avis_news_>("testModel1.fk_avis_collaborateur", "Avis_news");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Avis_news_>("testModel1.fk_avis_collaborateur", "Avis_news", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_commentaire_collaborateur", "Commentaire")]
        public EntityCollection<Commentaire_> Commentaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commentaire_>("testModel1.fk_commentaire_collaborateur", "Commentaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commentaire_>("testModel1.fk_commentaire_collaborateur", "Commentaire", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_like_news_collaborateur", "Like_news")]
        public EntityCollection<Like_news_> Like_news
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Like_news_>("testModel1.fk_like_news_collaborateur", "Like_news");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Like_news_>("testModel1.fk_like_news_collaborateur", "Like_news", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_message_collaborateur", "Message")]
        public EntityCollection<Message_> Message
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Message_>("testModel1.fk_message_collaborateur", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Message_>("testModel1.fk_message_collaborateur", "Message", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_poster_news_collaborateur", "News")]
        public EntityCollection<News_> News
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<News_>("testModel1.fk_poster_news_collaborateur", "News");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<News_>("testModel1.fk_poster_news_collaborateur", "News", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Avis_news_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Avis_news_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Avis_news_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="texte">Initial value of the texte property.</param>
        public static Avis_news_ CreateAvis_news_(global::System.Int32 id, global::System.String texte)
        {
            Avis_news_ avis_news_ = new Avis_news_();
            avis_news_.id = id;
            avis_news_.texte = texte;
            return avis_news_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> collaborateur_id
        {
            get
            {
                return _collaborateur_id;
            }
            set
            {
                Oncollaborateur_idChanging(value);
                ReportPropertyChanging("collaborateur_id");
                _collaborateur_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collaborateur_id");
                Oncollaborateur_idChanged();
            }
        }
        private Nullable<global::System.Int32> _collaborateur_id;
        partial void Oncollaborateur_idChanging(Nullable<global::System.Int32> value);
        partial void Oncollaborateur_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> news_id
        {
            get
            {
                return _news_id;
            }
            set
            {
                Onnews_idChanging(value);
                ReportPropertyChanging("news_id");
                _news_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("news_id");
                Onnews_idChanged();
            }
        }
        private Nullable<global::System.Int32> _news_id;
        partial void Onnews_idChanging(Nullable<global::System.Int32> value);
        partial void Onnews_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                OntexteChanging(value);
                ReportPropertyChanging("texte");
                _texte = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("texte");
                OntexteChanged();
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_avis_collaborateur", "Agent")]
        public Agent_ Agent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_avis_collaborateur", "Agent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_avis_collaborateur", "Agent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Agent_> AgentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_avis_collaborateur", "Agent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Agent_>("testModel1.fk_avis_collaborateur", "Agent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_avis_news", "News")]
        public News_ News
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<News_>("testModel1.fk_avis_news", "News").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<News_>("testModel1.fk_avis_news", "News").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<News_> NewsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<News_>("testModel1.fk_avis_news", "News");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<News_>("testModel1.fk_avis_news", "News", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Commentaire_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commentaire_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Commentaire_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="texte">Initial value of the texte property.</param>
        public static Commentaire_ CreateCommentaire_(global::System.Int32 id, global::System.String texte)
        {
            Commentaire_ commentaire_ = new Commentaire_();
            commentaire_.id = id;
            commentaire_.texte = texte;
            return commentaire_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> theme_id
        {
            get
            {
                return _theme_id;
            }
            set
            {
                Ontheme_idChanging(value);
                ReportPropertyChanging("theme_id");
                _theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("theme_id");
                Ontheme_idChanged();
            }
        }
        private Nullable<global::System.Int32> _theme_id;
        partial void Ontheme_idChanging(Nullable<global::System.Int32> value);
        partial void Ontheme_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> message_id
        {
            get
            {
                return _message_id;
            }
            set
            {
                Onmessage_idChanging(value);
                ReportPropertyChanging("message_id");
                _message_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("message_id");
                Onmessage_idChanged();
            }
        }
        private Nullable<global::System.Int32> _message_id;
        partial void Onmessage_idChanging(Nullable<global::System.Int32> value);
        partial void Onmessage_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> collaborateur_id
        {
            get
            {
                return _collaborateur_id;
            }
            set
            {
                Oncollaborateur_idChanging(value);
                ReportPropertyChanging("collaborateur_id");
                _collaborateur_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collaborateur_id");
                Oncollaborateur_idChanged();
            }
        }
        private Nullable<global::System.Int32> _collaborateur_id;
        partial void Oncollaborateur_idChanging(Nullable<global::System.Int32> value);
        partial void Oncollaborateur_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                OntexteChanging(value);
                ReportPropertyChanging("texte");
                _texte = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("texte");
                OntexteChanged();
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dating
        {
            get
            {
                return _dating;
            }
            set
            {
                OndatingChanging(value);
                ReportPropertyChanging("dating");
                _dating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dating");
                OndatingChanged();
            }
        }
        private Nullable<global::System.DateTime> _dating;
        partial void OndatingChanging(Nullable<global::System.DateTime> value);
        partial void OndatingChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_commentaire_collaborateur", "Agent")]
        public Agent_ Agent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_commentaire_collaborateur", "Agent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_commentaire_collaborateur", "Agent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Agent_> AgentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_commentaire_collaborateur", "Agent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Agent_>("testModel1.fk_commentaire_collaborateur", "Agent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_comm_theme_id", "Theme")]
        public Theme_ Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_comm_theme_id", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_comm_theme_id", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme_> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_comm_theme_id", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme_>("testModel1.fk_comm_theme_id", "Theme", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_message_id", "Message")]
        public Message_ Message
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Message_>("testModel1.fk_message_id", "Message").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Message_>("testModel1.fk_message_id", "Message").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Message_> MessageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Message_>("testModel1.fk_message_id", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Message_>("testModel1.fk_message_id", "Message", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Like_news_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Like_news_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Like_news_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Like_news_ CreateLike_news_(global::System.Int32 id)
        {
            Like_news_ like_news_ = new Like_news_();
            like_news_.id = id;
            return like_news_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> collaborateur_id
        {
            get
            {
                return _collaborateur_id;
            }
            set
            {
                Oncollaborateur_idChanging(value);
                ReportPropertyChanging("collaborateur_id");
                _collaborateur_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collaborateur_id");
                Oncollaborateur_idChanged();
            }
        }
        private Nullable<global::System.Int32> _collaborateur_id;
        partial void Oncollaborateur_idChanging(Nullable<global::System.Int32> value);
        partial void Oncollaborateur_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> news_id
        {
            get
            {
                return _news_id;
            }
            set
            {
                Onnews_idChanging(value);
                ReportPropertyChanging("news_id");
                _news_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("news_id");
                Onnews_idChanged();
            }
        }
        private Nullable<global::System.Int32> _news_id;
        partial void Onnews_idChanging(Nullable<global::System.Int32> value);
        partial void Onnews_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_like_news_collaborateur", "Agent")]
        public Agent_ Agent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_like_news_collaborateur", "Agent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_like_news_collaborateur", "Agent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Agent_> AgentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_like_news_collaborateur", "Agent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Agent_>("testModel1.fk_like_news_collaborateur", "Agent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_like_news_news", "News")]
        public News_ News
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<News_>("testModel1.fk_like_news_news", "News").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<News_>("testModel1.fk_like_news_news", "News").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<News_> NewsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<News_>("testModel1.fk_like_news_news", "News");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<News_>("testModel1.fk_like_news_news", "News", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Message_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="texte">Initial value of the texte property.</param>
        public static Message_ CreateMessage_(global::System.Int32 id, global::System.String texte)
        {
            Message_ message_ = new Message_();
            message_.id = id;
            message_.texte = texte;
            return message_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> theme_id
        {
            get
            {
                return _theme_id;
            }
            set
            {
                Ontheme_idChanging(value);
                ReportPropertyChanging("theme_id");
                _theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("theme_id");
                Ontheme_idChanged();
            }
        }
        private Nullable<global::System.Int32> _theme_id;
        partial void Ontheme_idChanging(Nullable<global::System.Int32> value);
        partial void Ontheme_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> collaborateur_id
        {
            get
            {
                return _collaborateur_id;
            }
            set
            {
                Oncollaborateur_idChanging(value);
                ReportPropertyChanging("collaborateur_id");
                _collaborateur_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collaborateur_id");
                Oncollaborateur_idChanged();
            }
        }
        private Nullable<global::System.Int32> _collaborateur_id;
        partial void Oncollaborateur_idChanging(Nullable<global::System.Int32> value);
        partial void Oncollaborateur_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                OntexteChanging(value);
                ReportPropertyChanging("texte");
                _texte = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("texte");
                OntexteChanged();
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dating
        {
            get
            {
                return _dating;
            }
            set
            {
                OndatingChanging(value);
                ReportPropertyChanging("dating");
                _dating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dating");
                OndatingChanged();
            }
        }
        private Nullable<global::System.DateTime> _dating;
        partial void OndatingChanging(Nullable<global::System.DateTime> value);
        partial void OndatingChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_message_collaborateur", "Agent")]
        public Agent_ Agent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_message_collaborateur", "Agent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_message_collaborateur", "Agent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Agent_> AgentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_message_collaborateur", "Agent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Agent_>("testModel1.fk_message_collaborateur", "Agent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_message_id", "Commentaire")]
        public EntityCollection<Commentaire_> Commentaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commentaire_>("testModel1.fk_message_id", "Commentaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commentaire_>("testModel1.fk_message_id", "Commentaire", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_theme_id", "Theme")]
        public Theme_ Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme_> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme_>("testModel1.fk_theme_id", "Theme", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="News_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class News_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new News_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="texte">Initial value of the texte property.</param>
        public static News_ CreateNews_(global::System.Int32 id, global::System.String texte)
        {
            News_ news_ = new News_();
            news_.id = id;
            news_.texte = texte;
            return news_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                OntexteChanging(value);
                ReportPropertyChanging("texte");
                _texte = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("texte");
                OntexteChanged();
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> collaborateur_id
        {
            get
            {
                return _collaborateur_id;
            }
            set
            {
                Oncollaborateur_idChanging(value);
                ReportPropertyChanging("collaborateur_id");
                _collaborateur_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("collaborateur_id");
                Oncollaborateur_idChanged();
            }
        }
        private Nullable<global::System.Int32> _collaborateur_id;
        partial void Oncollaborateur_idChanging(Nullable<global::System.Int32> value);
        partial void Oncollaborateur_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dating
        {
            get
            {
                return _dating;
            }
            set
            {
                OndatingChanging(value);
                ReportPropertyChanging("dating");
                _dating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dating");
                OndatingChanged();
            }
        }
        private Nullable<global::System.DateTime> _dating;
        partial void OndatingChanging(Nullable<global::System.DateTime> value);
        partial void OndatingChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_poster_news_collaborateur", "Agent")]
        public Agent_ Agent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_poster_news_collaborateur", "Agent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_poster_news_collaborateur", "Agent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Agent_> AgentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agent_>("testModel1.fk_poster_news_collaborateur", "Agent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Agent_>("testModel1.fk_poster_news_collaborateur", "Agent", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_avis_news", "Avis_news")]
        public EntityCollection<Avis_news_> Avis_news
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Avis_news_>("testModel1.fk_avis_news", "Avis_news");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Avis_news_>("testModel1.fk_avis_news", "Avis_news", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_like_news_news", "Like_news")]
        public EntityCollection<Like_news_> Like_news
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Like_news_>("testModel1.fk_like_news_news", "Like_news");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Like_news_>("testModel1.fk_like_news_news", "Like_news", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Stat_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stat_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stat_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Stat_ CreateStat_(global::System.Int32 id)
        {
            Stat_ stat_ = new Stat_();
            stat_.id = id;
            return stat_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> theme_id
        {
            get
            {
                return _theme_id;
            }
            set
            {
                Ontheme_idChanging(value);
                ReportPropertyChanging("theme_id");
                _theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("theme_id");
                Ontheme_idChanged();
            }
        }
        private Nullable<global::System.Int32> _theme_id;
        partial void Ontheme_idChanging(Nullable<global::System.Int32> value);
        partial void Ontheme_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nombre_vues
        {
            get
            {
                return _nombre_vues;
            }
            set
            {
                Onnombre_vuesChanging(value);
                ReportPropertyChanging("nombre_vues");
                _nombre_vues = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nombre_vues");
                Onnombre_vuesChanged();
            }
        }
        private Nullable<global::System.Int32> _nombre_vues;
        partial void Onnombre_vuesChanging(Nullable<global::System.Int32> value);
        partial void Onnombre_vuesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_theme_id_stat", "Theme")]
        public Theme_ Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id_stat", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id_stat", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme_> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme_>("testModel1.fk_theme_id_stat", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme_>("testModel1.fk_theme_id_stat", "Theme", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="stat_light_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class stat_light_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new stat_light_ object.
        /// </summary>
        /// <param name="texte">Initial value of the texte property.</param>
        public static stat_light_ Createstat_light_(global::System.String texte)
        {
            stat_light_ stat_light_ = new stat_light_();
            stat_light_.texte = texte;
            return stat_light_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                if (_texte != value)
                {
                    OntexteChanging(value);
                    ReportPropertyChanging("texte");
                    _texte = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("texte");
                    OntexteChanged();
                }
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nombre_vues
        {
            get
            {
                return _nombre_vues;
            }
            set
            {
                Onnombre_vuesChanging(value);
                ReportPropertyChanging("nombre_vues");
                _nombre_vues = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nombre_vues");
                Onnombre_vuesChanged();
            }
        }
        private Nullable<global::System.Int32> _nombre_vues;
        partial void Onnombre_vuesChanging(Nullable<global::System.Int32> value);
        partial void Onnombre_vuesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> theme_id
        {
            get
            {
                return _theme_id;
            }
            set
            {
                Ontheme_idChanging(value);
                ReportPropertyChanging("theme_id");
                _theme_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("theme_id");
                Ontheme_idChanged();
            }
        }
        private Nullable<global::System.Int32> _theme_id;
        partial void Ontheme_idChanging(Nullable<global::System.Int32> value);
        partial void Ontheme_idChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Theme_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Theme_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Theme_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="texte">Initial value of the texte property.</param>
        public static Theme_ CreateTheme_(global::System.Int32 id, global::System.String texte)
        {
            Theme_ theme_ = new Theme_();
            theme_.id = id;
            theme_.texte = texte;
            return theme_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String texte
        {
            get
            {
                return _texte;
            }
            set
            {
                OntexteChanging(value);
                ReportPropertyChanging("texte");
                _texte = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("texte");
                OntexteChanged();
            }
        }
        private global::System.String _texte;
        partial void OntexteChanging(global::System.String value);
        partial void OntexteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_theme_id_abonnement", "Abonnement")]
        public EntityCollection<Abonnement_> Abonnement
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Abonnement_>("testModel1.fk_theme_id_abonnement", "Abonnement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Abonnement_>("testModel1.fk_theme_id_abonnement", "Abonnement", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_comm_theme_id", "Commentaire")]
        public EntityCollection<Commentaire_> Commentaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commentaire_>("testModel1.fk_comm_theme_id", "Commentaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commentaire_>("testModel1.fk_comm_theme_id", "Commentaire", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_theme_id", "Message")]
        public EntityCollection<Message_> Message
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Message_>("testModel1.fk_theme_id", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Message_>("testModel1.fk_theme_id", "Message", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_theme_id_stat", "Stat")]
        public EntityCollection<Stat_> Stat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stat_>("testModel1.fk_theme_id_stat", "Stat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stat_>("testModel1.fk_theme_id_stat", "Stat", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel1", Name="Type_")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Type_ : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Type_ object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="type1">Initial value of the type1 property.</param>
        public static Type_ CreateType_(global::System.Int32 id, global::System.String type1)
        {
            Type_ type_ = new Type_();
            type_.id = id;
            type_.type1 = type1;
            return type_;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type1
        {
            get
            {
                return _type1;
            }
            set
            {
                Ontype1Changing(value);
                ReportPropertyChanging("type1");
                _type1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type1");
                Ontype1Changed();
            }
        }
        private global::System.String _type1;
        partial void Ontype1Changing(global::System.String value);
        partial void Ontype1Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("testModel1", "fk_agent", "Agent")]
        public EntityCollection<Agent_> Agent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Agent_>("testModel1.fk_agent", "Agent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Agent_>("testModel1.fk_agent", "Agent", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
